
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author muhammad rifky alfarez (201851041)
 */
public class NilaiMakul extends javax.swing.JFrame {

    /**
     * Creates new form Nilai
     */
    public NilaiMakul() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbonim = new javax.swing.JComboBox<>();
        txtnama = new javax.swing.JTextField();
        txtmakul = new javax.swing.JTextField();
        cbonilai = new javax.swing.JComboBox<>();
        cmdsave = new javax.swing.JButton();
        cmdupdate = new javax.swing.JButton();
        cmddelete = new javax.swing.JButton();
        cmdcancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tnilaimakul = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("DATA NILAI MATA KULIAH");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("NIM");

        jLabel3.setText("NAMA");

        jLabel4.setText("MAKUL");

        jLabel5.setText("NILAI");

        cbonim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH NIM" }));
        cbonim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbonimActionPerformed(evt);
            }
        });

        cbonilai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "A", "AB", "B", "BC", "C", "CD", "D", "E" }));

        cmdsave.setText("SAVE");
        cmdsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsaveActionPerformed(evt);
            }
        });

        cmdupdate.setText("UPDATE");
        cmdupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdupdateActionPerformed(evt);
            }
        });

        cmddelete.setText("DELETE");
        cmddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmddeleteActionPerformed(evt);
            }
        });

        cmdcancel.setText("CANCEL");
        cmdcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbonilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmakul, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbonim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmddelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdcancel)
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbonim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmakul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbonilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdsave)
                    .addComponent(cmdupdate)
                    .addComponent(cmddelete)
                    .addComponent(cmdcancel))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jLabel6.setText("SEARCH");

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        tnilaimakul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tnilaimakul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tnilaimakulMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tnilaimakul);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    /*
    NAMA  : MUHAMMAD RIFKY ALFAREZ
    NIM   : 201851041
    KELAS : E
    */
    String koneksi="jdbc:mysql://localhost/dbakademik";
    String user="root";
    String pass="";
    Connection connection;
    Statement statement;
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        try {
            Class.forName ("com.mysql.jdbc.Driver"); 
            koneksi="jdbc:mysql://localhost/dbakademik";
            connection= (Connection) DriverManager.getConnection(koneksi,user,pass);
            statement=(Statement) connection.createStatement ();
            
            String nims="select nim from mahasiswa order by nim asc";
            ResultSet res=statement.executeQuery(nims);
            
            while (res.next()) {
                cbonim.addItem(res.getString("nim"));
            }
        }
        catch (Exception DBException){
            JOptionPane.showMessageDialog (this, "koneksi gagal", "Error", JOptionPane. ERROR_MESSAGE) ;
            System.err.println("Error:"+DBException);
        }
        bersih ();
        cmdupdate.setEnabled (false);
        cmddelete.setEnabled (false);
        cbonim.requestFocus();
        txtnama.setEditable(false);
    }                                 

    private void cmdsaveActionPerformed(java.awt.event.ActionEvent evt) {                                        
        try{
            String sql;
            {
                sql="insert into nilaimakul value('";
                sql+=cbonim.getSelectedItem()+"','";
                sql+=txtmakul.getText()+"','";
                sql+=cbonilai.getSelectedItem()+"')";
            }
            statement.executeUpdate(sql);
                JOptionPane.showMessageDialog(this,"Simpan data berhasil","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception DBException){
           JOptionPane.showMessageDialog(this,"Simpan data gagal","Error",JOptionPane.ERROR_MESSAGE);
            System.err.println("Error:"+DBException);
        }
        bersih();
        cbonim.setSelectedIndex(0);
    }                                       

    private void cmdupdateActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try{
            String sql;
            {
                sql="update nilaimakul set makul='";
                sql+=txtmakul.getText()+"',nilai='";
                sql+=cbonilai.getSelectedItem()+"'";
                sql+="where nim='";
                sql+=cbonim.getSelectedItem()+"'";
                sql+="AND makul='"+txtmakul.getText()+"'";
            }
            statement.executeUpdate(sql);
                JOptionPane.showMessageDialog(this,"Update data berhasil","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception DBException){
           JOptionPane.showMessageDialog(this,"Update data gagal","Error",JOptionPane.ERROR_MESSAGE);
            System.err.println("Error:"+DBException);
        }
        bersih();
        cbonim.setSelectedIndex(0);
        cbonilai.setSelectedIndex(0);
        cmdsave.setEnabled(true);
        cmdupdate.setEnabled (false);
        cmddelete.setEnabled (false);
    }                                         

    private void cmddeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try{
            int reply=JOptionPane.showConfirmDialog(this,
                    "Apakah anda yakin akan menghapus data ini?",
                    "Konfirmasi",JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            if (reply==JOptionPane.YES_OPTION) {
                String sql="delete from nilaimakul where nim='"+cbonim.getSelectedItem()
                        +"' AND makul='"+txtmakul.getText()+"'";
                statement.executeUpdate(sql);
            }
        }catch(Exception DBException){
            JOptionPane.showMessageDialog(this,"Hapus data gagal","Error",JOptionPane.ERROR_MESSAGE);
            System.err.println("Error"+DBException);
        }
        bersih();
        cbonim.requestFocus();
        cmdsave.setEnabled(true);
        cmdupdate.setEnabled (false);
        cmddelete.setEnabled (false);
    }                                         

    private void cmdcancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
        dispose();
    }                                         

    private void tnilaimakulMouseClicked(java.awt.event.MouseEvent evt) {                                         
        cbonim.setSelectedItem(tnilaimakul.getValueAt(tnilaimakul.getSelectedRow(),0).toString());
        txtnama.setText(tnilaimakul.getValueAt(tnilaimakul.getSelectedRow(),1).toString());
        txtmakul.setText(tnilaimakul.getValueAt(tnilaimakul.getSelectedRow(),2).toString());
        cbonilai.setSelectedItem(tnilaimakul.getValueAt(tnilaimakul.getSelectedRow(),3).toString());
        cbonim.setEditable(false);
        txtnama.setEditable(false);
        txtmakul.setEditable(false);
        cmdsave.setEnabled(false);
        cmdupdate.setEnabled (true);
        cmddelete.setEnabled (true);
    }                                        

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {                                   
        DefaultTableModel tabel=new DefaultTableModel();
            tabel.addColumn("NIM");
            tabel.addColumn("NAMA");
            tabel.addColumn("MAKUL");
            tabel.addColumn("NILAI");

        try{
            String sql="select nm.nim, nama, makul, nilai "
                    + "from nilaimakul nm, mahasiswa mhs WHERE nm.nim like '%"+txtcari.getText()+"%'"
                    + "or nama like '%"+txtcari.getText()+"%'"
                    + "or makul like '%"+txtcari.getText()+"%'"
                    + "or nilai like '%"+txtcari.getText()+"%'"
                    + "AND mhs.nim=nm.nim";
            ResultSet rs=statement.executeQuery(sql);
            while(rs.next()){
                tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                });
            }
            tnilaimakul.setModel(tabel);
        }
        catch(Exception DBException){
            System.err.println("Error ="+DBException);
        }
    }                                  

    private void cbonimActionPerformed(java.awt.event.ActionEvent evt) {                                       
        try{
            String nm="select * from mahasiswa where nim='"
                +cbonim.getSelectedItem()+"'";
            ResultSet rst=statement.executeQuery(nm);
            while(rst.next()){
                txtnama.setText(rst.getString("nama"));
            }
        }
        catch(Exception DBException){
            System.err.println("Error:"+DBException);
        }
    }                                      
    
    private void bersih(){
        cbonim.setSelectedIndex(0);
        txtnama.setText("");
        txtmakul.setText("");
        cbonilai.setSelectedIndex(0);
        
        try{
            String sql="select nm.nim, mhs.nama, nm.makul, nm.nilai ";
                   sql+="from mahasiswa mhs, nilaimakul nm ";
                   sql+="WHERE mhs.nim=nm.nim";
            ResultSet rs=(ResultSet) statement.executeQuery(sql);
            final String[] header={"NIM","NAMA","MAKUL","NILAI"};
            rs.last();
            int n=rs.getRow();
            Object[][] data=new Object[n][4];
            int p=0;
            rs.beforeFirst();
            while (rs.next()) {
                data[p][0]=rs.getString(1);
                data[p][1]=rs.getString(2);
                data[p][2]=rs.getString(3);
                data[p][3]=rs.getString(4);
                p++;
            }
            
            tnilaimakul.setModel(new javax.swing.table.DefaultTableModel(data, header));
            tnilaimakul.setAlignmentX(CENTER_ALIGNMENT);
            
            
            
        }catch(Exception DBException){
            System.err.println("Error:"+DBException);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/pcbonim         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NilaiMakul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NilaiMakul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NilaiMakul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NilaiMakul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NilaiMakul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> cbonilai;
    private javax.swing.JComboBox<String> cbonim;
    private javax.swing.JButton cmdcancel;
    private javax.swing.JButton cmddelete;
    private javax.swing.JButton cmdsave;
    private javax.swing.JButton cmdupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tnilaimakul;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtmakul;
    private javax.swing.JTextField txtnama;
    // End of variables declaration                   
}
